email: ""
raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
outputdir: "/work/$USER/output16S"
taxonomy:
  mothur:
    do: true
    db_path: "../DBs/amplicon"
    tax_db: "SILVA_138_SSURef_NR99_prok.515F.806R"
  decipher:
    do: false
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
primers:
  fwd: 
    sequence: GTGYCAGCMGCCGCGGTAA
    name: 515F
  rvs: 
    sequence: GGACTACNVGGGTWTCTAAT
    name: 806R
paired: true
sequencing_direction: "unknown"
filtering:
  trunc_length:
    fwd: 170
    rvs: 130
  trunc_qual: 13
  max_EE:
    fwd: 0.2
    rvs: 0.2
  minLen:
    fwd: 0
    rvs: 0
  maxLen:
    fwd: Inf
    rvs: Inf
  minQ:
    fwd: 0
    rvs: 0
blast:
  do: true
hand_off:
  biom: true
  phyloseq: false
final_table_filtering:
  do: true
  keep_target_taxa: "."
  target_min_length: 245
  target_max_length: 275
postprocessing:
  rarefaction_curve: true
  funguild:
    do: false
  treeing:
    do: true
